//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace demoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.ProductoAlmacen = new HashSet<ProductoAlmacen>();
        }


        public string Nombre { get; set; }
        [DisplayName("Ciudad")]
        [Required]

        public string Ciudad { get; set; }
        [DisplayName("Código postal")]
        [Required]
        [RegularExpression("^[0-9]{5}$",
            ErrorMessage = "Código postal incorrecto")]

        public int CP { get; set; }


        public int idAlmacen { get; set; }
        [DisplayName("Nombre")]
        [Required]
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAlmacen> ProductoAlmacen { get; set; }
    }
}
